<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TSLAB_5</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>001cf512-5614-4e98-8bcc-0285e30e5d22</testSuiteGuid>
   <testCaseLink>
      <guid>1dbe578d-4ca9-4827-83a7-e7dff5d86c70</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6771533-a146-4f3e-a563-afc91c8aecc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3323f25d-a9c0-48ae-98d9-760c56f99187</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0c15852-d3b0-4ff9-bce4-495e03bea581</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC02</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fee198fc-049f-488d-8579-850e0f6ed5b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>468ace31-bebe-473f-b2c2-a5fdae92fffa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7f603ae3-0da3-49a2-a87e-d970135fe2ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC03</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfc234c6-b4ff-45e2-88c3-5de21bbedab9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0d7ca82-a76c-4408-9b9c-e9de753fcf59</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>826ceaf6-6e70-4525-be44-a3f7f30b0fde</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC04</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4037e222-0d0f-4ac1-8bca-3872310acb51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d34b88a7-e79f-45e6-aa26-ff4b5b7b93f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e92fe220-f716-4144-9740-c2509b17e517</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC05</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>140c3ff2-a9ad-40b8-8cc1-fdf6de096d5d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca4ee4e6-dfbc-4bb7-a674-a7c9a2309cab</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
